const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{janela: 0},
	{Solid: 0},
	{suporte: 0},
	{bau: 0},
	{Platform: 0},
	{caixa: 0},
	{porta: 0},
	{ScrollTo: 0},
	{Jogador: 0},
	{Sensor_solido: 0},
	{Direcao: 0},
	{Flash: 0},
	{porco_patrulheiro: 0},
	{sensor_patrulheiro_direita: 0},
	{sensor_patrulheiro_esquerda: 0},
	{Keyboard: 0},
	{VIDA_HUD: 0},
	{ITENS_HUD: 0},
	{Fundo_preto: 0},
	{jogador_dialogo: 0},
	{SpriteFont: 0},
	{porco_canhao: 0},
	{Canhao: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{BALA: 0},
	{SENSOR_CANHAO: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sensor_solido: class extends self.ISpriteInstance {},
	porco_patrulheiro: class extends self.ISpriteInstance {},
	sensor_patrulheiro_direita: class extends self.ISpriteInstance {},
	sensor_patrulheiro_esquerda: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	VIDA_HUD: class extends self.ISpriteInstance {},
	ITENS_HUD: class extends self.ISpriteInstance {},
	Fundo_preto: class extends self.ISpriteInstance {},
	jogador_dialogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	porco_canhao: class extends self.ISpriteInstance {},
	Canhao: class extends self.ISpriteInstance {},
	BALA: class extends self.ISpriteInstance {},
	SENSOR_CANHAO: class extends self.ISpriteInstance {}
}